#!/bin/bash
if [[ $1 == "" ]] ; then
    echo man2html bash
    exit;
fi

d=/tmp
outfile=$d/$1.htm
if [ -e $outfile ];then
    firefox $outfile
    exit
fi
tmpfile=$d/a.htm
prefile=$d/pre.htm
mainfile=$d/main.htm
man -L en $1 > $tmpfile
sed -n '/\(^\([A-Z]\+\s*\)\+\)$/s//<a href="#\1">\1<\/a><p>/p' $tmpfile> $prefile
sed '{s/</\&lt;/g}; {s/>/\&gt;/g}' $tmpfile | sed '/\(^\([A-Z]\+\s*\)\+\)$/s//<pre><text id="\1">\1<\/text>/'> $mainfile
cat $prefile $mainfile > $outfile
firefox $outfile
